quarkus:
  http:
    cors:
      ~: true
      origins: /.*/
  datasource:
    db-kind: postgresql
    username: postgres
    password: mysecretpassword
    jdbc:
      url: jdbc:postgresql://localhost:5432/c24tipping
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: update

c24tipping:
  adminPW: admin123
